name: Dequeue external contributor PR after push

on:
  pull_request_target:
    types: [synchronize, reopened]

permissions:
  issues: write

jobs:
  remove_automerge_contrib_label:
    # is PR event triggered from fork
    if: github.event.pull_request.head.repo.full_name != github.event.pull_request.base.repo.full_name
    runs-on: ubuntu-latest
    steps:
    - name: Remove automerge_contrib trigger label
      uses: andymckay/labeler@e6c4322d0397f3240f0e7e30a33b5c5df2d39e90
      with:
        remove-labels: automerge-contrib
