name: "Lint+Test"
on:
  pull_request:
  push:
    branches:
      - main
      - devnet
      - testnet
      - auto
      - canary
      - staging
      - stuff5
      - testing
      - pr-mirror/**

jobs:
  scripts-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: sleep 45

  e2e-lint:
    runs-on: ubuntu-latest
    if: github.event.pull_request.head.repo.full_name == github.event.pull_request.base.repo.full_name
    steps:
      - uses: actions/checkout@v3
      - run: sleep 90
